gem/Gemfile: Remove google
Dead.

    > google hello
    Error: Google Search API Status 403. Details:
    The Google Web Search API is no longer available. Please migrate to the
    Google
    Custom Search API (https://developers.google.com/custom-search/)
    Try again in a moment.
    Try --help for help.